version: 3

tasks:
  init:
    cmds:
      - cargo install diesel_cli
      - touch api/local.db.sqlite3
      - mkcert localhost
      - cd app && pnpm i
      - cd api && cargo build
  dev:back:
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: actix_web=info
    cmds:
      - cd api && cargo watch -x 'run --bin api'
  dev:front:
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    cmds:
      - cd app && pnpm run dev --https

