version: 3

tasks:
  init:
    cmds:
      - cd app && pnpm i
      - cd api && cargo build
  dev:back:
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: actix_web=info
    cmds:
      - cd api && cargo watch -x 'run --bin api'
  dev:front:
    cmds:
      - cd app && pnpm run dev

